/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Donor;

import Business.EcoSystem;
import Business.UserAccount.DonorAccount;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiahuanli
 */
public class OthersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OthersJPanel
     */
    JPanel donorContainer;
    EcoSystem system;
    ArrayList<DonorAccount> donorAccountList;

    public OthersJPanel(JPanel donorContainer, EcoSystem system) {
        initComponents();
        this.donorContainer = donorContainer;
        this.system = system;
        populateDonateInformationTable();

        for (UserAccount account : system.getUserAccountDirectory().getUserAccountList()) {
            System.out.println(account.getRole().getClass().getTypeName());
            if (account.getRole().getClass().getTypeName().equals("Business.Role.DonorRole")) {
                DonorAccount donorAccount = (DonorAccount) account;
                for (WorkRequest workRequest : system.getWorkQueue().getWorkRequestList()) {
                    if (workRequest.getSender().equals(account)) {
                        if (donorAccount.getTotalAmount() == 0.0) {
                            if (workRequest.getMoney() != null) {
                                donorAccount.setTotalAmount(donorAccount.getTotalAmount() + workRequest.getMoney());
                            } else {
                                donorAccount.setTotalAmount(donorAccount.getTotalAmount() + (workRequest.getItem().getQuantity() * workRequest.getItem().getPrice()));
                            }
                        }else if(donorAccount.getTotalAmount() != 0.0){
                        if (workRequest.getMoney() != null) {
                                donorAccount.setTotalAmount(donorAccount.getTotalAmount() + workRequest.getMoney());
                            } else {
                                donorAccount.setTotalAmount(donorAccount.getTotalAmount() + (workRequest.getItem().getQuantity() * workRequest.getItem().getPrice()));
                            }
                        }
                    }
                }
            }
        }

        donorAccountList = new ArrayList<DonorAccount>();

        for (UserAccount account : system.getUserAccountDirectory().getUserAccountList()) {
            if (account.getRole().getClass().getTypeName().equals("Business.Role.DonorRole")) {
                DonorAccount donorAccount = (DonorAccount) account;
                donorAccountList.add(donorAccount);
            }
        }

        Collections.sort(donorAccountList);
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonateInformation = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtDonorName = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTop = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnSearchTop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View Others");

        tblDonateInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name", "Name", "Amount", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonateInformation);
        if (tblDonateInformation.getColumnModel().getColumnCount() > 0) {
            tblDonateInformation.getColumnModel().getColumn(0).setResizable(false);
            tblDonateInformation.getColumnModel().getColumn(1).setResizable(false);
            tblDonateInformation.getColumnModel().getColumn(2).setResizable(false);
            tblDonateInformation.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setText("Donor Name:");

        tblTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Name", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTop);
        if (tblTop.getColumnModel().getColumnCount() > 0) {
            tblTop.getColumnModel().getColumn(0).setResizable(false);
            tblTop.getColumnModel().getColumn(1).setResizable(false);
            tblTop.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSearchTop.setText("Top List");
        btnSearchTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTopActionPerformed(evt);
            }
        });

        jLabel5.setText("search Donor Top List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(406, 406, 406)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSearchTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchTop))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        int rc = tblDonateInformation.getModel().getRowCount() - 1;
        while (rc >= 0) {
            ((DefaultTableModel) tblDonateInformation.getModel()).removeRow(rc);
            rc = rc - 1;
        }

        for (WorkRequest workRequest : system.getWorkQueue().getWorkRequestList()) {
            if (workRequest.getSender().getPerson().getName().equals(txtDonorName.getText())) {
                Object[] row = new Object[4];

                if (workRequest.getMoney() == null) {
                    row[0] = workRequest.getSender().getPerson().getName();
                    row[1] = workRequest.getItem().getName();
                    row[2] = workRequest.getItem().getQuantity();
                    row[3] = workRequest.getRequestDate();
                    ((DefaultTableModel) tblDonateInformation.getModel()).addRow(row);
                } else {
                    row[0] = workRequest.getSender().getPerson().getName();
                    row[1] = "Money";
                    row[2] = workRequest.getMoney();
                    row[3] = workRequest.getRequestDate();
                    ((DefaultTableModel) tblDonateInformation.getModel()).addRow(row);
                }

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTopActionPerformed
        populateTop();
// TODO add your handling code here:
    }//GEN-LAST:event_btnSearchTopActionPerformed

    public void populateDonateInformationTable() {
        int rc = tblDonateInformation.getModel().getRowCount() - 1;
        while (rc >= 0) {
            ((DefaultTableModel) tblDonateInformation.getModel()).removeRow(rc);
            rc = rc - 1;
        }

        for (WorkRequest workRequest : system.getWorkQueue().getWorkRequestList()) {
//            if (workRequest.getSender().getRole().equals("Business.Role.DonorRole")) {
            Object[] row = new Object[4];
            if (workRequest.getMoney() == null) {
                row[0] = workRequest.getSender().getPerson().getName();
                row[1] = workRequest.getItem().getName();
                row[2] = workRequest.getItem().getQuantity();
                row[3] = workRequest.getRequestDate();
                ((DefaultTableModel) tblDonateInformation.getModel()).addRow(row);
            } else {
                row[0] = workRequest.getSender().getPerson().getName();
                row[1] = "Money";
                row[2] = workRequest.getMoney();
                row[3] = workRequest.getRequestDate();
                ((DefaultTableModel) tblDonateInformation.getModel()).addRow(row);
            }
//            }
        }

    }

    public void populateTop() {
        int rc = tblTop.getModel().getRowCount() - 1;
        while (rc >= 0) {
            ((DefaultTableModel) tblTop.getModel()).removeRow(rc);
            rc = rc - 1;
        }
        int top = 0;
        for (DonorAccount donorAccount : donorAccountList) {
            Object[] row = new Object[3];

            row[0] = ++top;
            row[1] = donorAccount.getUsername();
            row[2] = donorAccount.getTotalAmount();
            ((DefaultTableModel) tblTop.getModel()).addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblDonateInformation;
    private javax.swing.JTable tblTop;
    private javax.swing.JTextField txtDonorName;
    // End of variables declaration//GEN-END:variables
}
