/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Victim;

import Business.Area.Area;
import Business.Country.Country;
import Business.District.District;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;

/**
 *
 * @author jiahuanli
 */
public class VictimWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VictimWorkAreaJPanel
     */
    JPanel container;
    UserAccount userAccount;
    Area area;
    District district;
    Country country;
    EcoSystem business;

    public VictimWorkAreaJPanel(JPanel container, UserAccount userAccount, Area area, District district) {
        initComponents();
        this.container = container;
        this.userAccount = userAccount;
        this.area = area;
        this.district = district;
        // this.country=country;
        // this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnRequest = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        victimContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnAccount.setText("Account Setting");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btnRequest)
                .addGap(27, 27, 27)
                .addComponent(btnAccount)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        victimContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(victimContainer);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        RequestJPanel rejp = new RequestJPanel(victimContainer, userAccount, area, district);
        victimContainer.add("RequestJPanel", rejp);
        ((java.awt.CardLayout) victimContainer.getLayout()).next(victimContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        SettingJPanel sjp = new SettingJPanel(victimContainer, userAccount);
        victimContainer.add("SettingJPanel", sjp);
        ((java.awt.CardLayout) victimContainer.getLayout()).next(victimContainer);
// TODO add your handling code here:
    }//GEN-LAST:event_btnAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnRequest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel victimContainer;
    // End of variables declaration//GEN-END:variables
}
