/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin.System;

import Interface.Admin.Country.ManageDistrictAdminJPanel;
import Interface.Admin.Country.ManageDistrictJPanel;
import Business.Area.Area;
import Business.Country.Country;
import Business.District.District;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jiahuanli
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount account;

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;

        populateTree();
    }

    public void populateTree() {

        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();

        ArrayList<Country> countryList = system.getCountryList();
        ArrayList<District> districtList;
        ArrayList<Area> areaList;
        Country country;
        District district;
        Area area;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Countries");
        //DefaultMutableTreeNode states = new DefaultMutableTreeNode("States");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode countryNode;
        DefaultMutableTreeNode districtNode;
        DefaultMutableTreeNode areaNode;
        for (int i = 0; i < countryList.size(); i++) {
            country = countryList.get(i);
            countryNode = new DefaultMutableTreeNode(country.getName());
            networks.insert(countryNode, i);
            // networkNode.insert(states, i);

            districtList = country.getDistrictDirectory().getDistrictList();
            for (int i1 = 0; i1 < districtList.size(); i1++) {
                district = districtList.get(i1);
                districtNode = new DefaultMutableTreeNode(district.getName());
                countryNode.insert(districtNode, i1);

                areaList = district.getAreaDirectory().getAreaList();
                for (int j = 0; j < areaList.size(); j++) {
                    area = areaList.get(j);
                   // if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Providor) {
                        areaNode = new DefaultMutableTreeNode(area.getName());
                        districtNode.insert(areaNode, j);
                    }
               // }
            }
        }
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblViewNode = new javax.swing.JLabel();
        btnManageStateAdmin1 = new javax.swing.JButton();
        btnManageStateAdmin2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();

        jSplitPane1.setDividerLocation(400);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnManageNetwork.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        btnManageNetwork.setText("Manage Country");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        jLabel1.setText("Selected Node:");

        lblViewNode.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        lblViewNode.setText("<view_selected_node>");

        btnManageStateAdmin1.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        btnManageStateAdmin1.setText("Manage Country Admin");
        btnManageStateAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStateAdmin1ActionPerformed(evt);
            }
        });

        btnManageStateAdmin2.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        btnManageStateAdmin2.setText("Adjust Inventory");
        btnManageStateAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStateAdmin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblViewNode))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnManageNetwork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageStateAdmin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageStateAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblViewNode))
                .addGap(50, 50, 50)
                .addComponent(btnManageNetwork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageStateAdmin1)
                .addGap(55, 55, 55)
                .addComponent(btnManageStateAdmin2)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        ManageCountryJPanel manageNetworkJPanel = new ManageCountryJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void JTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) JTree.getLastSelectedPathComponent();
        if (selectedNode != null) {
            lblViewNode.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_JTreeValueChanged

    private void btnManageStateAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStateAdmin1ActionPerformed
        // TODO add your handling code here:
        ManageCountryAdminJPanel manageCountryAdminJPanel = new ManageCountryAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageCountryAdminJPanel", manageCountryAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStateAdmin1ActionPerformed

    private void btnManageStateAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStateAdmin2ActionPerformed
        // TODO add your handling code here:
        AdjustJPanel manageCountryAdminJPanel = new AdjustJPanel(userProcessContainer, system);
        userProcessContainer.add("AdjustJPanel", manageCountryAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStateAdmin2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageStateAdmin1;
    private javax.swing.JButton btnManageStateAdmin2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblViewNode;
    // End of variables declaration//GEN-END:variables
}
