/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Salesperson;

import Business.Market.MarketList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liuch
 */
public class ManageCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomerJPanel
     */
    private MarketList marketList;
    private JPanel userProcessContainer;
    public ManageCustomerJPanel(MarketList marketList,JPanel userProcessContainer) {
        initComponents();
        this.marketList=marketList;
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowCustomer = new javax.swing.JButton();
        btnShowCustomer1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btnShowCustomer.setText("Add New Customer >>");
        btnShowCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCustomerActionPerformed(evt);
            }
        });

        btnShowCustomer1.setText("Show customer　＞＞");
        btnShowCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCustomer1ActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(349, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnShowCustomer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCustomer1ActionPerformed
   ShowCustomerJPanel awajp = new ShowCustomerJPanel(marketList,userProcessContainer);
    userProcessContainer.add("ShowCustomerJPanel ",awajp);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
      layout.next(userProcessContainer);           // TODO add your handling code here:
    }//GEN-LAST:event_btnShowCustomer1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnShowCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCustomerActionPerformed
    NewCustomerJPanel awajp = new NewCustomerJPanel(marketList,userProcessContainer);
    userProcessContainer.add("ServeCustomerJPanel ",awajp);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
      layout.next(userProcessContainer);     
        

   // TODO add your handling code here:
    }//GEN-LAST:event_btnShowCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowCustomer;
    private javax.swing.JButton btnShowCustomer1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
