/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Salesperson;



import Business.Admin.UserAccount;
import Business.Market.Customer;
import Business.Market.MarketList;
import Business.Market.MarketOfferCatalog;
import Business.SalesPerson.SalesPerson;
import Business.SalesPerson.SalesPersonDirectory;
import Business.Supplier.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liuch
 */
public class SalesmanMainJFrame extends javax.swing.JPanel {

    /**
     * Creates new form SalesmanMainJFrame
     */
    MarketList marketList;
    SupplierDirectory supplierDirectory;
    JPanel userProcessContainer;
    SalesPerson pointedSm ;
    UserAccount account;
    SalesPersonDirectory salesPersonDirectory;
    MarketOfferCatalog marketOfferCatalog;
    public SalesmanMainJFrame(SalesPersonDirectory salesPersonDirectory,MarketList marketList,SupplierDirectory supplierDirectory,JPanel userProcessContainer,SalesPerson pointedSm,UserAccount account,MarketOfferCatalog marketOfferCatalog) {
        initComponents();
        this.marketList=marketList;
        this.supplierDirectory=supplierDirectory;
        this.userProcessContainer=userProcessContainer;
        this.pointedSm=pointedSm;
        this.account=account;
        this.salesPersonDirectory=salesPersonDirectory;
        this.marketOfferCatalog=marketOfferCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustomerName = new javax.swing.JTextField();
        btnServeCustomer = new javax.swing.JButton();
        btnManageCustomer = new java.awt.Button();

        btnServeCustomer.setText("Serve Customer");
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });

        btnManageCustomer.setLabel("Manage customer");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnServeCustomer)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed
    
    Customer customer=marketList.searchCustomer(txtCustomerName.getText());
    if(customer==null)
    {
         JOptionPane.showMessageDialog(null,"Customer not exist");
         return;
    }
    ServeCustomerJPanel awajp = new ServeCustomerJPanel(salesPersonDirectory,marketList,supplierDirectory,userProcessContainer,pointedSm,account,customer,marketOfferCatalog);
    userProcessContainer.add("ServeCustomerJPanel ",awajp);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
      layout.next(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnServeCustomerActionPerformed

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
     ManageCustomerJPanel awajp = new ManageCustomerJPanel(marketList,userProcessContainer);
    userProcessContainer.add("ManageCustomerJPanel ",awajp);
     CardLayout layout = (CardLayout)userProcessContainer.getLayout();
      layout.next(userProcessContainer);     
         
  



// TODO add your handling code here:
    }//GEN-LAST:event_btnManageCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnManageCustomer;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JTextField txtCustomerName;
    // End of variables declaration//GEN-END:variables
}
