/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Airport.Airline;
import Airport.Airplane;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiahuanli
 */
public class ViewAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneJPanel
     */
    private Airline al;
    private Airline searchResult;
    public ViewAirplaneJPanel(Airline al) {
        initComponents();
        this.al = al;
        searchResult = new Airline();
        populateTable();
        
    }
    
    public void populateTable(){
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(Airplane ap : al.getAirline()){
            Object row[] = new Object[7];
            row[0] = ap;
            row[1] = ap.getCompany();
            row[2] = ap.getModelNum();
            row[3] = ap.getSeatsNum();
            row[4] = (int)ap.getDepartureHour()+":"+ap.getDepartureMin();
            row[5] = (int)ap.getCertYear()+"/"+ap.getCertMon();
            row[6] = ap.getProductYear();
            dtm.addRow(row);
        }
    }
    
    public void addToTable(Airplane ad){
            DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
            Object row[] = new Object[7];
            row[0] = ad;
            row[1] = ad.getCompany();
            row[2] = ad.getModelNum();
            row[3] = ad.getSeatsNum();
            row[4] = (int)ad.getDepartureHour()+":"+ad.getDepartureMin();
            row[5] = (int)ad.getCertYear()+"/"+ad.getCertMon();
            row[6] = ad.getProductYear();
            dtm.addRow(row);
    }
    
    public void saveResult(Airplane result){
        Airplane sr = searchResult.addAirplane();
        sr.setCertYear(result.getCertYear());
        sr.setCertMon(result.getCertMon());
        sr.setCompany(result.getCompany());
        sr.setDepartureHour(result.getDepartureHour());
        sr.setDepartureMin(result.getDepartureMin());
        sr.setModelNum(result.getModelNum());
        sr.setProductYear(result.getProductYear());
        sr.setSeatsNum(result.getSeatsNum());
        sr.setSerialNum(result.getSerialNum());
        searchResult.setUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneTable = new javax.swing.JTable();
        detailBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        companyTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productYearTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialNumTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seatsNumTextField = new javax.swing.JTextField();
        modelNumTextField = new javax.swing.JTextField();
        changeBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        certYearTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        certMonTextField = new javax.swing.JTextField();
        departureHourTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        departureMinTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        firstPlaneBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nowHourTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nowMinTextField = new javax.swing.JTextField();
        countBtn = new javax.swing.JButton();
        avaNumTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        nonavaNumTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        madeByBtn = new javax.swing.JButton();
        madeByTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        proYearTextField = new javax.swing.JTextField();
        proYearBtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        seatMaxTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        seatMinTextField = new javax.swing.JTextField();
        seatBtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        findSerialTextField = new javax.swing.JTextField();
        findSerialBtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        findModelTextField = new javax.swing.JTextField();
        findModelBtn = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        maderTbl = new javax.swing.JTable();
        maderTblBtn = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        showUpdateBtn = new javax.swing.JButton();
        showUpdateTextField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        expireYearTextField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        expireMonTextField = new javax.swing.JTextField();
        expireBtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        secondTextField = new javax.swing.JTextField();
        showAllBtn = new javax.swing.JButton();
        secondBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("View Airline");

        airplaneTable.setBackground(null);
        airplaneTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        airplaneTable.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 16)); // NOI18N
        airplaneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Company", "Model Number", "Seats", "Departure Time", "Certificate Expried Date", "Production Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airplaneTable.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(airplaneTable);

        detailBtn.setBackground(new java.awt.Color(255, 255, 255));
        detailBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        detailBtn.setText("View & Change");
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel4.setText("Company");

        companyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel5.setText("Production Year");

        productYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productYearTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel6.setText("Certificate Expire Date");

        jLabel7.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel7.setText("Departure Time");

        jLabel2.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel2.setText("Serial Number");

        serialNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel8.setText("Seats");

        jLabel3.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel3.setText("Model Number");

        seatsNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsNumTextFieldActionPerformed(evt);
            }
        });

        modelNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNumTextFieldActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(255, 255, 255));
        changeBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        changeBtn.setText("Upate");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setText("Search Airplane");

        jLabel10.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("Update Info");

        certYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certYearTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel11.setText("year");

        jLabel12.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel12.setText("month");

        certMonTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certMonTextFieldActionPerformed(evt);
            }
        });

        departureHourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureHourTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel13.setText("hour");

        jLabel14.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel14.setText("min");

        departureMinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureMinTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel15.setText("1. first available plane");

        firstPlaneBtn.setBackground(new java.awt.Color(255, 255, 255));
        firstPlaneBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        firstPlaneBtn.setText("Find Plane");
        firstPlaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPlaneBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel16.setText("2.Numbers of plane");

        jLabel17.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel17.setText("available");

        nowHourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowHourTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel18.setText("hour");

        jLabel19.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel19.setText("min");

        nowMinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowMinTextFieldActionPerformed(evt);
            }
        });

        countBtn.setBackground(new java.awt.Color(255, 255, 255));
        countBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        countBtn.setText("number");
        countBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel20.setText("nonavailable");

        jLabel21.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel21.setText("3. Manufacturers(Boeing)");

        madeByBtn.setBackground(new java.awt.Color(255, 255, 255));
        madeByBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        madeByBtn.setText("Find");
        madeByBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madeByBtnActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel22.setText("4. Production Year");

        proYearBtn.setBackground(new java.awt.Color(255, 255, 255));
        proYearBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        proYearBtn.setText("Find");
        proYearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proYearBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel23.setText("5. Seats");

        jLabel24.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel24.setText("Max");

        jLabel25.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel25.setText("Min");

        seatBtn.setBackground(new java.awt.Color(255, 255, 255));
        seatBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        seatBtn.setText("Find");
        seatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatBtnActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel26.setText("6.Serial Number ");

        findSerialBtn.setBackground(new java.awt.Color(255, 255, 255));
        findSerialBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        findSerialBtn.setText("Find");
        findSerialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findSerialBtnActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel27.setText("7.Model Number ");

        findModelBtn.setBackground(new java.awt.Color(255, 255, 255));
        findModelBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        findModelBtn.setText("Find");
        findModelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findModelBtnActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel28.setText("8. Manufacturers List");

        maderTbl.setBackground(null);
        maderTbl.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        maderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "manufacturers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        maderTbl.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(maderTbl);

        maderTblBtn.setBackground(new java.awt.Color(255, 255, 255));
        maderTblBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        maderTblBtn.setText("Create");
        maderTblBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maderTblBtnActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel29.setText("9. Update Time");

        showUpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        showUpdateBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        showUpdateBtn.setText("show");
        showUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUpdateBtnActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel30.setText("11. expired maintenance certificate ");

        jLabel31.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel31.setText("Year");

        jLabel32.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel32.setText("Month");

        expireBtn.setBackground(new java.awt.Color(255, 255, 255));
        expireBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        expireBtn.setText("Find");
        expireBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireBtnActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        jLabel33.setText("Bonus: Secondary Filter");

        comboBox.setBackground(null);
        comboBox.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company", "Serial Number", "Model Number", "Production Year" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        secondTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondTextFieldActionPerformed(evt);
            }
        });

        showAllBtn.setBackground(new java.awt.Color(255, 255, 255));
        showAllBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        showAllBtn.setText("Show All Data");
        showAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllBtnActionPerformed(evt);
            }
        });

        secondBtn.setBackground(new java.awt.Color(255, 255, 255));
        secondBtn.setFont(new java.awt.Font("Abadi MT Condensed Light", 1, 14)); // NOI18N
        secondBtn.setText("Find");
        secondBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(detailBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(showAllBtn))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel22)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel24)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(firstPlaneBtn)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(proYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(seatMaxTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                                            .addComponent(findSerialTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(findModelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(proYearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel25))
                                                            .addComponent(findSerialBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(findModelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(madeByTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(madeByBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(nowHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel19))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(avaNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel20)))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(nowMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(nonavaNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(seatMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(seatBtn))))))
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(expireBtn))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel33)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel28)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(maderTblBtn))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel29)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(showUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(showUpdateTextField))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(secondBtn))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel31)
                                                .addGap(18, 18, 18)
                                                .addComponent(expireYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(expireMonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(countBtn)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(productYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)))))))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(523, 523, 523)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(certYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departureHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatsNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(5, 5, 5)
                                                .addComponent(departureMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(certMonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {certMonTextField, certYearTextField, companyTextField, departureHourTextField, departureMinTextField, modelNumTextField, productYearTextField, seatsNumTextField, serialNumTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {expireBtn, findModelBtn, findSerialBtn, madeByBtn, maderTblBtn, proYearBtn, seatBtn, showUpdateBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {avaNumTextField, expireMonTextField, expireYearTextField, findModelTextField, findSerialTextField, madeByTextField, nonavaNumTextField, nowHourTextField, nowMinTextField, proYearTextField, seatMaxTextField, seatMinTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailBtn)
                    .addComponent(deleteBtn)
                    .addComponent(showAllBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(certMonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(seatsNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(certYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(serialNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(companyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(modelNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(departureHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(departureMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(changeBtn)
                        .addComponent(productYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(firstPlaneBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nowHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(nowMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(maderTblBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(avaNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(madeByTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(madeByBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(nonavaNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(proYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proYearBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seatMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25)
                                .addComponent(seatMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatBtn)
                                .addComponent(jLabel24))
                            .addComponent(jLabel23))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(findSerialBtn)
                                    .addComponent(findSerialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(findModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findModelBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(showUpdateBtn))
                        .addGap(2, 2, 2)
                        .addComponent(showUpdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(expireBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(expireYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(expireMonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondBtn))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void companyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTextFieldActionPerformed

    private void productYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productYearTextFieldActionPerformed

    private void serialNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumTextFieldActionPerformed

    private void seatsNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsNumTextFieldActionPerformed

    private void modelNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNumTextFieldActionPerformed

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airplaneTable.getSelectedRow();
        if (selectedRow >= 0){
            Airplane ap = (Airplane)airplaneTable.getValueAt(selectedRow,0);
            departureHourTextField.setText(String.valueOf(ap.getDepartureHour()));
            departureMinTextField.setText(String.valueOf(ap.getDepartureMin()));
            companyTextField.setText(ap.getCompany());
            productYearTextField.setText(String.valueOf(ap.getProductYear()));
            seatsNumTextField.setText(String.valueOf(ap.getSeatsNum()));
            serialNumTextField.setText(ap.getSerialNum());
            modelNumTextField.setText(ap.getModelNum());
            certYearTextField.setText(String.valueOf(ap.getCertYear()));  
            certMonTextField.setText(String.valueOf(ap.getCertMon()));
        }else
            JOptionPane.showMessageDialog(null, "Please select any row");
    }//GEN-LAST:event_detailBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = airplaneTable.getSelectedRow();
        if (selectedRow >= 0){
            Airplane ap = (Airplane)airplaneTable.getValueAt(selectedRow,0);
            al.deleteAirplane(ap);
            JOptionPane.showMessageDialog(null, "Deleted!");
            al.setUpdate();
            populateTable();
        }else
            JOptionPane.showMessageDialog(null, "Please select any row");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        // TODO add your handling code here:
        if(departureHourTextField.getText().isEmpty()|departureMinTextField.getText().isEmpty()|companyTextField.getText().isEmpty()
                |productYearTextField.getText().isEmpty()|seatsNumTextField.getText().isEmpty()|
                serialNumTextField.getText().isEmpty()|modelNumTextField.getText().isEmpty()|certYearTextField.getText().isEmpty()
                |certMonTextField.getText().isEmpty()
                ){
            JOptionPane.showMessageDialog(null, "Please enter complete the form!");
        }else if(Integer.parseInt(departureHourTextField.getText())>24|Integer.parseInt(departureMinTextField.getText())>60
                |Integer.parseInt(productYearTextField.getText())>2017|Integer.parseInt(certYearTextField.getText())>99
                |Integer.parseInt(certMonTextField.getText())>12){
            JOptionPane.showMessageDialog(null, "Please enter the correct info!");
        }else{
        int selectedRow = airplaneTable.getSelectedRow();
        if (selectedRow >= 0){
            Airplane ap = (Airplane)airplaneTable.getValueAt(selectedRow,0);
            
        int departureHour = Integer.parseInt(departureHourTextField.getText());
        int departureMin = Integer.parseInt(departureMinTextField.getText());
        String company = companyTextField.getText();
        int productYear = Integer.parseInt(productYearTextField.getText());
        int seatsNum = Integer.parseInt(seatsNumTextField.getText());
        String serialNum = serialNumTextField.getText();
        String modelNum = modelNumTextField.getText();
        int certYear = Integer.parseInt(certYearTextField.getText());
        int certMon = Integer.parseInt(certMonTextField.getText());
        
        ap.setCertYear(certYear);
        ap.setCertMon(certMon);
        ap.setCompany(company);
        ap.setDepartureHour(departureHour);
        ap.setDepartureMin(departureMin);
        ap.setModelNum(modelNum);
        ap.setProductYear(productYear);
        ap.setSeatsNum(seatsNum);
        ap.setSerialNum(serialNum);
        al.setUpdate();
        JOptionPane.showMessageDialog(null, "Updated!");
        
        departureHourTextField.setText("");
        departureMinTextField.setText("");
        companyTextField.setText("");
        productYearTextField.setText("");
        seatsNumTextField.setText("");
        serialNumTextField.setText("");
        modelNumTextField.setText("");
        certYearTextField.setText("");
        certMonTextField.setText("");
        
        populateTable();
        
       
        }else
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
    }//GEN-LAST:event_changeBtnActionPerformed

    private void certYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certYearTextFieldActionPerformed

    private void certMonTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certMonTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certMonTextFieldActionPerformed

    private void departureHourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureHourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureHourTextFieldActionPerformed

    private void departureMinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureMinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureMinTextFieldActionPerformed

    private void firstPlaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPlaneBtnActionPerformed
        // TODO add your handling code here:
        Airplane min = new Airplane();
        min = al.minDepartureTime();  
        //show on the table
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        searchResult.getAirline().clear();
        saveResult(min);
        addToTable(min);
    }//GEN-LAST:event_firstPlaneBtnActionPerformed

    private void nowHourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowHourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nowHourTextFieldActionPerformed

    private void nowMinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowMinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nowMinTextFieldActionPerformed

    private void countBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countBtnActionPerformed
        // TODO add your handling code here:
        int nowHour = Integer.parseInt(nowHourTextField.getText());
        int nowMin = Integer.parseInt(nowMinTextField.getText());
        int availableNum = al.availableNum(nowHour, nowMin);
        avaNumTextField.setText(String.valueOf(availableNum));
        nonavaNumTextField.setText(String.valueOf(al.getAirline().size()-availableNum));
    }//GEN-LAST:event_countBtnActionPerformed

    private void madeByBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madeByBtnActionPerformed
        // TODO add your handling code here:
        String company = madeByTextField.getText();
        Airplane samemader = new Airplane();
        searchResult.getAirline().clear();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareCom = al.getAirline().get(i).getCompany();
            if(company.equals(compareCom)){
                samemader = al.getAirline().get(i);
                saveResult(samemader);
                addToTable(samemader);
            }     
        }
        
    }//GEN-LAST:event_madeByBtnActionPerformed

    private void proYearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proYearBtnActionPerformed
        // TODO add your handling code here:
        int proYear = Integer.parseInt(proYearTextField.getText());
        Airplane samePro = new Airplane();
        searchResult.getAirline().clear();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            int comparePro = al.getAirline().get(i).getProductYear();
            if(comparePro == proYear){
                samePro = al.getAirline().get(i);
                saveResult(samePro);
                addToTable(samePro);
            }     
        }
    }//GEN-LAST:event_proYearBtnActionPerformed

    private void seatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatBtnActionPerformed
        // TODO add your handling code here:
        int seatMax = Integer.parseInt(seatMaxTextField.getText());
        int seatMin = Integer.parseInt(seatMinTextField.getText());
        searchResult.getAirline().clear();
        Airplane seatAp = new Airplane();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            int seats = al.getAirline().get(i).getSeatsNum();
            if(seats<=seatMax & seats>=seatMin){
                seatAp = al.getAirline().get(i);
                saveResult(seatAp);
                addToTable(seatAp);
            }     
        }
    }//GEN-LAST:event_seatBtnActionPerformed

    private void findSerialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findSerialBtnActionPerformed
        // TODO add your handling code here:
        String serialNum = findSerialTextField.getText();
        Airplane exap = new Airplane();
        searchResult.getAirline().clear();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareSer = al.getAirline().get(i).getSerialNum();
            if(serialNum.equals(compareSer)){
                exap = al.getAirline().get(i);
                saveResult(exap);
                addToTable(exap);
            }     
        }
    }//GEN-LAST:event_findSerialBtnActionPerformed

    private void findModelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findModelBtnActionPerformed
        // TODO add your handling code here:
        String modelNum = findModelTextField.getText();
        Airplane exap = new Airplane();
        searchResult.getAirline().clear();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareModel = al.getAirline().get(i).getModelNum();
            if(modelNum.equals(compareModel)){
                exap = al.getAirline().get(i);
                saveResult(exap);
                addToTable(exap);
            }     
        }
    }//GEN-LAST:event_findModelBtnActionPerformed

    private void maderTblBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maderTblBtnActionPerformed
        // TODO add your handling code here:
        int size = al.getAirline().size();
        String[] mader = new String[size];
        DefaultTableModel maderlist =(DefaultTableModel)maderTbl.getModel();
        maderlist.setRowCount(0);
        for(int i=0;i<size;i++){
            mader[i] = new String(al.getAirline().get(i).getCompany());
        }
        
        HashSet<String> set=new HashSet<String>();
           for(int i=0;i<size;i++){
              set.add(mader[i]); 
         }
        Iterator<String> itr=set.iterator(); 
        
            Object row[] = new Object[1];
            while(itr.hasNext()){  
            row[0] = itr.next();
            maderlist.addRow(row);
             }           
    }//GEN-LAST:event_maderTblBtnActionPerformed

    private void showUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUpdateBtnActionPerformed
        // TODO add your handling code here:
        String update = String.valueOf(al.getUpdate());
        if(!update.isEmpty()){
            showUpdateTextField.setText(update);
        }else{ 
            System.out.println("1");
            JOptionPane.showMessageDialog(null, "No update");
        }
    }//GEN-LAST:event_showUpdateBtnActionPerformed

    private void expireBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireBtnActionPerformed
        // TODO add your handling code here:
        int expireYear = Integer.parseInt(expireYearTextField.getText());
        int expireMon = Integer.parseInt(expireMonTextField.getText());
        searchResult.getAirline().clear();
        Airplane exap = new Airplane();
        int size = al.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            int compareYear = al.getAirline().get(i).getCertYear(); 
            int compareMon = al.getAirline().get(i).getCertMon();
            if(expireYear >= compareYear & expireMon > compareMon){
                exap = al.getAirline().get(i);
                saveResult(exap);
                addToTable(exap);
            } 
        }
    }//GEN-LAST:event_expireBtnActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboBoxActionPerformed

    private void secondTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondTextFieldActionPerformed

    private void showAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_showAllBtnActionPerformed

    private void secondBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondBtnActionPerformed
        // TODO add your handling code here:
        Object selected = comboBox.getSelectedItem();
        if(selected.toString().equals("Company")){
        String company = secondTextField.getText();
        Airplane samemader = new Airplane();
        int size = searchResult.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareCom = searchResult.getAirline().get(i).getCompany();
            if(company.equals(compareCom)){
                samemader = searchResult.getAirline().get(i);
                addToTable(samemader);
            } 
        }
        }else if(selected.toString().equals("Serial Number")){
        String serialNum = secondTextField.getText();
        Airplane exap = new Airplane();
        int size = searchResult.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareSer = searchResult.getAirline().get(i).getSerialNum();
            if(serialNum.equals(compareSer)){
                exap = searchResult.getAirline().get(i);
                addToTable(exap);
            }  
            System.out.println("Serial Number");
        }
        }else if(selected.toString().equals("Model Number")){
        String modelNum = secondTextField.getText();
        Airplane exap = new Airplane();
        int size = searchResult.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            String compareModel = searchResult.getAirline().get(i).getModelNum();
            if(modelNum.equals(compareModel)){
                exap = searchResult.getAirline().get(i);
                addToTable(exap);
            }     
        }
        }else if(selected.toString().equals("Production Year")){
        int proYear = Integer.parseInt(secondTextField.getText());
        Airplane samePro = new Airplane();
        int size = searchResult.getAirline().size();
        int i;
        DefaultTableModel dtm =(DefaultTableModel)airplaneTable.getModel();
        dtm.setRowCount(0);
        for(i=0;i<size;i++){
            int comparePro = searchResult.getAirline().get(i).getProductYear();
            if(comparePro == proYear){
                samePro = searchResult.getAirline().get(i);
                addToTable(samePro);
            }     
        }
        }
    }//GEN-LAST:event_secondBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airplaneTable;
    private javax.swing.JTextField avaNumTextField;
    private javax.swing.JTextField certMonTextField;
    private javax.swing.JTextField certYearTextField;
    private javax.swing.JButton changeBtn;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JButton countBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField departureHourTextField;
    private javax.swing.JTextField departureMinTextField;
    private javax.swing.JButton detailBtn;
    private javax.swing.JButton expireBtn;
    private javax.swing.JTextField expireMonTextField;
    private javax.swing.JTextField expireYearTextField;
    private javax.swing.JButton findModelBtn;
    private javax.swing.JTextField findModelTextField;
    private javax.swing.JButton findSerialBtn;
    private javax.swing.JTextField findSerialTextField;
    private javax.swing.JButton firstPlaneBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton madeByBtn;
    private javax.swing.JTextField madeByTextField;
    private javax.swing.JTable maderTbl;
    private javax.swing.JButton maderTblBtn;
    private javax.swing.JTextField modelNumTextField;
    private javax.swing.JTextField nonavaNumTextField;
    private javax.swing.JTextField nowHourTextField;
    private javax.swing.JTextField nowMinTextField;
    private javax.swing.JButton proYearBtn;
    private javax.swing.JTextField proYearTextField;
    private javax.swing.JTextField productYearTextField;
    private javax.swing.JButton seatBtn;
    private javax.swing.JTextField seatMaxTextField;
    private javax.swing.JTextField seatMinTextField;
    private javax.swing.JTextField seatsNumTextField;
    private javax.swing.JButton secondBtn;
    private javax.swing.JTextField secondTextField;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JButton showUpdateBtn;
    private javax.swing.JTextField showUpdateTextField;
    // End of variables declaration//GEN-END:variables
}
