/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Command;

import Business.Area.Area;
import Business.District.District;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiahuanli
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountsJPanel
     */
    JPanel CommandContainer;
    UserAccount useraccount;
    District district;

    ManageUserAccountJPanel(JPanel CommandContainer, UserAccount useraccount, District district) {
        initComponents();
        this.CommandContainer = CommandContainer;
        this.useraccount = useraccount;
        this.district = district;
        populateFrontline();
        populatePurchase();

    }

    public void populateFrontline() {
        DefaultTableModel dtm = (DefaultTableModel) tblFrontline.getModel();
        dtm.setRowCount(0);
        
        for (Area area : district.getAreaDirectory().getAreaList()) {
            for (UserAccount useraccount : area.getUserAccountDirectory().getUserAccountList()) {             
                if (useraccount.getRole().getClass().getTypeName().equals("Business.Role.FrontLineRole")) {
                    Object row[] = new Object[3];
                    row[0] = useraccount;
                    row[1] = "Front Line";
                    row[2] = useraccount.getPerson();
                    dtm.addRow(row);
                }

            }
        }
    }

    public void populatePurchase() {
        DefaultTableModel dtm = (DefaultTableModel) tblPurchase.getModel();
        dtm.setRowCount(0);

        for (UserAccount useraccount : district.getUserAccountDirectory().getUserAccountList()) {    
            if (useraccount.getRole().getClass().getTypeName().equals("Business.Role.PurchaseRole")) {
                Object row[] = new Object[3];
                row[0] = useraccount;
                row[1] = "Purchase";
                row[2] = useraccount.getPerson();
                dtm.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        btnDeleteF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFrontline = new javax.swing.JTable();
        btnDeleteP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        jLabel1.setText("Manage UserAccount");

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Role", "Person"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPurchase);
        if (tblPurchase.getColumnModel().getColumnCount() > 0) {
            tblPurchase.getColumnModel().getColumn(0).setResizable(false);
            tblPurchase.getColumnModel().getColumn(1).setResizable(false);
            tblPurchase.getColumnModel().getColumn(2).setResizable(false);
        }

        btnDeleteF.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteF.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        btnDeleteF.setText("Delete");
        btnDeleteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFActionPerformed(evt);
            }
        });

        tblFrontline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Role", "Person"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFrontline);
        if (tblFrontline.getColumnModel().getColumnCount() > 0) {
            tblFrontline.getColumnModel().getColumn(0).setResizable(false);
            tblFrontline.getColumnModel().getColumn(1).setResizable(false);
            tblFrontline.getColumnModel().getColumn(2).setResizable(false);
        }

        btnDeleteP.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteP.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        btnDeleteP.setText("Delete");
        btnDeleteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        jLabel2.setText("Purchase");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        jLabel3.setText("Frontline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteP)
                    .addComponent(btnDeleteF))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel3)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnDeleteF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteP)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFActionPerformed
        int selectedRow = tblFrontline.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first", "Warning", JOptionPane.WARNING_MESSAGE);
            populateFrontline();
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int DialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account?", "Warning", dialogButton);
            if (DialogResult == JOptionPane.YES_OPTION) {
                UserAccount ua = (UserAccount) tblFrontline.getValueAt(selectedRow, 0);
                for (Area area : district.getAreaDirectory().getAreaList()) {
                    for (UserAccount user : area.getUserAccountDirectory().getUserAccountList()) {
                        if (user.equals(ua)) {
                            area.getUserAccountDirectory().deleteUserAccount(ua);
                            break;
                        }
                    }
                    break;
                }
                populateFrontline();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteFActionPerformed

    private void btnDeletePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePActionPerformed
        int selectedRow = tblPurchase.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first", "Warning", JOptionPane.WARNING_MESSAGE);
            populatePurchase();
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int DialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account?", "Warning", dialogButton);
            if (DialogResult == JOptionPane.YES_OPTION) {
                UserAccount ua = (UserAccount) tblPurchase.getValueAt(selectedRow, 0);
                for (UserAccount user : district.getUserAccountDirectory().getUserAccountList()) {
                    if (user.equals(ua)) {
                        district.getUserAccountDirectory().deleteUserAccount(ua);
                        break;
                    }
                }

              populatePurchase();  
            }
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletePActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteF;
    private javax.swing.JButton btnDeleteP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFrontline;
    private javax.swing.JTable tblPurchase;
    // End of variables declaration//GEN-END:variables
}
