/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jiahuanli
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    private JPanel rightJPanel;
    private TravelAgency travelAgency;
    private AirlinerDirectory airlinerDirectory;
    
    ManageAirlinersJPanel(JPanel rightPanel, TravelAgency travelAgency) {
        initComponents();
        this.rightJPanel = rightPanel;
        this.travelAgency = travelAgency;
        airlinerDirectory = travelAgency.getAirlinerDirectory();
        populateTable();
    }
    private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblManageAirliners.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner: airlinerDirectory.getAirlinerDirectory()){
            Object[] row = new Object[4];
            row[0] = airliner;
            row[1] = airliner.getAirlineName();
            row[2] = airliner.getTotalFlightPerDay();
            row[3] = airliner.getFlightSchedule();
            
            dtm.addRow(row);
        }
    }

    /**
     * Creates new form ManageAirlinersJPanel
     */



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageAirliners = new javax.swing.JTable();
        btnNewAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefreash = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Airliners");

        tblManageAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Number", "Airliner Name", "Number of Flights", "FlightSchedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageAirliners);
        if (tblManageAirliners.getColumnModel().getColumnCount() > 0) {
            tblManageAirliners.getColumnModel().getColumn(0).setResizable(false);
            tblManageAirliners.getColumnModel().getColumn(1).setResizable(false);
            tblManageAirliners.getColumnModel().getColumn(2).setResizable(false);
            tblManageAirliners.getColumnModel().getColumn(3).setResizable(false);
        }

        btnNewAirliner.setText("New Airliner");
        btnNewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setText("View Airliner");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Airliner");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefreash.setText("Refresh Table");
        btnRefreash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreash)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNewAirliner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewAirliner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAirliner)
                    .addComponent(btnViewAirliner)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRefreash)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAirlinerActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel panel = new CreateNewAirlinerJPanel(rightJPanel,airlinerDirectory);
        rightJPanel.add("CreateNewAirlinerJPanel",panel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnNewAirlinerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliners.getSelectedRow();
         if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select!");
  
         }else{
             Airliner airliner = (Airliner)tblManageAirliners.getValueAt(selectedRow,0);
             ViewAirlinerJPanel panel = new ViewAirlinerJPanel(rightJPanel,airliner);
             rightJPanel.add("ViewAirlinerJPanel",panel);
             CardLayout layout = (CardLayout)rightJPanel.getLayout();
             layout.next(rightJPanel);
         }
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliners.getSelectedRow();
        if(selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the Airliner?","Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_NO_OPTION){
                Airliner airliner = (Airliner)tblManageAirliners.getValueAt(selectedRow, 0);
                airlinerDirectory.deleteAccount(airliner);
                populateTable();
            }
        }else{
                    JOptionPane.showMessageDialog(null, "Please select!");

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreashActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNewAirliner;
    private javax.swing.JButton btnRefreash;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageAirliners;
    // End of variables declaration//GEN-END:variables
}
